### ISSUE TITLE
EV.py paper/live trading giving traceback error

### ISSUE THREAD

**Issue by ch0wdan** [litepresence/extinction-event#5]
I am having some issues trying to get paper trading/live trading to work. Curious if anyone has any ideas on what this is caused by?

Thanks

```
EXTINCTION EVENT v0.00000007 niceties

0:OPTIMIZE, 1:BACKTEST, 2:PAPER, 3:LIVE, 4:SALES, 6: TEST ORDERS
TRADING MODE: 2

Traceback (most recent call last):
  File "EV/EV.py", line 3427, in <module>
    keys_install()
  File "EV/EV.py", line 284, in keys_install
    nodes = nodes_fetch()
  File "EV/EV.py", line 617, in nodes_fetch
    return metaNODE['whitelist']
KeyError: 'whitelist'
```

**Comment by ch0wdan** [comment]
I believe the reason I am seeing this error is because `metaNODE.py` is not saving any calls as whitelisted. When running it, I get a TON of `valueerror()`, with some "whitelisted" ones, however tailing metaNODE.txt I am just getting `{}`

**Comment by ch0wdan** [comment]
While trying to debug what is going on, I've figured out that `microDEX.py` doesn't like my account name for some reason. Every time I provide my username, I am getting `AccountDoesNotExistsException try again`. I am not sure exactly why, but I am able to log into my account via the web client and the standalone client 😞

**Comment by ch0wdan** [comment]
@litepresence can you give some guidance possibly?
